"use client";

import { useState } from "react";
import { signUp } from "@/lib/auth/actions";

export default function SignupPage() {
  const [message, setMessage] = useState<string | null>(null);
    const [error, setError] = useState<string | null>(null);

      async function handleSubmit(formData: FormData) {
          setError(null);
              setMessage(null);
                  const result = await signUp(formData);
                      if (result?.error) setError(result.error);
                          if (result?.success) setMessage(result.message ?? "Check your email.");
                            }

                              return (
                                  <div className="flex min-h-screen items-center justify-center bg-[#0B0F14] px-4">
                                        <div className="w-full max-w-sm rounded-xl border border-white/10 bg-[#11161D] p-8 shadow-xl">
                                                <h1 className="mb-1 text-2xl font-semibold text-white">Create account</h1>
                                                        <p className="mb-6 text-sm text-white/50">Join Dispatch Desk V2</p>

                                                                <form action={handleSubmit} className="space-y-4">
                                                                          <div>
                                                                                      <label className="mb-1 block text-sm text-white/70">Full name</label>
                                                                                                  <input
                                                                                                                type="text"
                                                                                                                              name="fullName"
                                                                                                                                            required
                                                                                                                                                          className="w-full rounded-md border border-white/10 bg-[#0B0F14] px-3 py-2 text-white outline-none focus:border-sky-500"
                                                                                                                                                                      />
                                                                                                                                                                                </div>

                                                                                                                                                                                          <div>
                                                                                                                                                                                                      <label className="mb-1 block text-sm text-white/70">Email</label>
                                                                                                                                                                                                                  <input
                                                                                                                                                                                                                                type="email"
                                                                                                                                                                                                                                              name="email"
                                                                                                                                                                                                                                                            required
                                                                                                                                                                                                                                                                          className="w-full rounded-md border border-white/10 bg-[#0B0F14] px-3 py-2 text-white outline-none focus:border-sky-500"
                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                          <div>
                                                                                                                                                                                                                                                                                                                      <label className="mb-1 block text-sm text-white/70">Password</label>
                                                                                                                                                                                                                                                                                                                                  <input
                                                                                                                                                                                                                                                                                                                                                type="password"
                                                                                                                                                                                                                                                                                                                                                              name="password"
                                                                                                                                                                                                                                                                                                                                                                            required
                                                                                                                                                                                                                                                                                                                                                                                          minLength={8}
                                                                                                                                                                                                                                                                                                                                                                                                        className="w-full rounded-md border border-white/10 bg-[#0B0F14] px-3 py-2 text-white outline-none focus:border-sky-500"
                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                        {error && <p className="text-sm text-red-400">{error}</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                  {message && <p className="text-sm text-emerald-400">{message}</p>}

                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="w-full rounded-md bg-sky-500 py-2 font-medium text-white transition hover:bg-sky-400"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Sign up
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </form>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="mt-6 text-center text-sm text-white/50">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Already have an account?{" "}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <a href="/login" className="text-sky-400 hover:underline">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Sign in
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  