import { signIn } from "@/lib/auth/actions";

export default async function LoginPage({
  searchParams,
  }: {
    searchParams: Promise<{ redirectTo?: string; error?: string }>;
    }) {
      const params = await searchParams;

        return (
            <div className="flex min-h-screen items-center justify-center bg-[#0B0F14] px-4">
                  <div className="w-full max-w-sm rounded-xl border border-white/10 bg-[#11161D] p-8 shadow-xl">
                          <h1 className="mb-1 text-2xl font-semibold text-white">Sign in</h1>
                                  <p className="mb-6 text-sm text-white/50">Dispatch Desk V2</p>

                                          <form action={signIn} className="space-y-4">
                                                    <input type="hidden" name="redirectTo" value={params.redirectTo ?? "/dashboard"} />

                                                              <div>
                                                                          <label className="mb-1 block text-sm text-white/70">Email</label>
                                                                                      <input
                                                                                                    type="email"
                                                                                                                  name="email"
                                                                                                                                required
                                                                                                                                              className="w-full rounded-md border border-white/10 bg-[#0B0F14] px-3 py-2 text-white outline-none focus:border-sky-500"
                                                                                                                                                          />
                                                                                                                                                                    </div>

                                                                                                                                                                              <div>
                                                                                                                                                                                          <label className="mb-1 block text-sm text-white/70">Password</label>
                                                                                                                                                                                                      <input
                                                                                                                                                                                                                    type="password"
                                                                                                                                                                                                                                  name="password"
                                                                                                                                                                                                                                                required
                                                                                                                                                                                                                                                              className="w-full rounded-md border border-white/10 bg-[#0B0F14] px-3 py-2 text-white outline-none focus:border-sky-500"
                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                              {params.error && (
                                                                                                                                                                                                                                                                                                          <p className="text-sm text-red-400">{decodeURIComponent(params.error)}</p>
                                                                                                                                                                                                                                                                                                                    )}

                                                                                                                                                                                                                                                                                                                              <button
                                                                                                                                                                                                                                                                                                                                          type="submit"
                                                                                                                                                                                                                                                                                                                                                      className="w-full rounded-md bg-sky-500 py-2 font-medium text-white transition hover:bg-sky-400"
                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                            Sign in
                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                              </form>

                                                                                                                                                                                                                                                                                                                                                                                                      <p className="mt-6 text-center text-sm text-white/50">
                                                                                                                                                                                                                                                                                                                                                                                                                No account?{" "}
                                                                                                                                                                                                                                                                                                                                                                                                                          <a href="/signup" className="text-sky-400 hover:underline">
                                                                                                                                                                                                                                                                                                                                                                                                                                      Sign up
                                                                                                                                                                                                                                                                                                                                                                                                                                                </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    